name: First Workflow
on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello, World!"
      - name: Multiline command
        run: |
          node -v
          npm -v
