name: Workflow Commands
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an Error Messsage
        run: echo "::error file=app.js,line=1,col=1::Missing semicolon"
      - name: Setting a Warning Message
        run: echo "::warning file=app.js,line=1,col=1::Missing semicolon"
      - name: Setting an Annotation
        run: echo "::annotation file=app.js,line=1,col=1::Missing semicolon"
      - name: Setting a Debug Message
        run: echo "::debug file=app.js,line=1,col=1 ::Missing semicolon"
